import React from 'react';
import styled from 'styled-components';
import ActionButton from '../components/Button/ActionButton';
import Navigation from '../components/Navigation';

//my note: everything should be a div unless if in this case for Logo
//its and img. then we can center and make it look nice
//ex was like for a header. can use h1 h2 etc..
//but can put it in a div and style it to be the size, position etc.

const Logo = styled.img`
  width: 75px;
  height 75px;
  position: absolute;
  z-index: 10;
  top: 25px;
  left: 25px;
`;

// ask Aaroh why this is wrong and why i need to call it "logo2"
// const profile_image = styled.img`
// 	width: 75px;
//   	height 75px;
//   	position: absolute;
// `;

const Logo2 = styled.img`
	width: 273px;
	height: 364px;
	border-radius: 50%;
`;

const Description = styled.p`
	color: ${({ theme }) => theme.black};
	font-size: 23px;
	text-align: center;
`;

const Description2 = styled.p`
	font-size: 23px;
	right: 25px;
`;

const Container = styled.div`
	width: 100vw;
	height: 100vh;
	background-color: ${({ theme }) => theme.pink};
	display: flex;
	flex-direction: column;
	justify-content: center;
	// font-size: 30px;
	top: -2px;
	align-items: center;
	& input {
		width: 100%;
	}
`;

const Section = styled.h1`
	color: ${({ theme }) => theme.white};
	font-family: 'Nunito', sans-serif;
	text-align: center;
	font-size: 50px;
`;

const Home = props => {
	return (
		<div>
			<Navigation />
			<Logo src="../static/wrapped_logo.png" alt="wrapped_logo" />
			<Container>
				<Section>Product Definition Statement</Section>
				<Description>
					At wrapped, our goal is to make it easy for you to show
					appreciation for your loved ones with the perfect gift,
					every time.
				</Description>
				<Section>What is wrapped?</Section>
				<Description>
					wrapped. is a web application that helps you find the
					perfect gift for your loved ones. We remind you when to
					purchase your gift with emails, and help you manage all the
					gifts you need to buy for any occasion!
					{/*In the future, we
					will include more features such as automated purchasing,
					money deposit, and reccomendations generated by machine
					learning!*/}
				</Description>
				<Section>Why wrapped?</Section>
				<Description2>
					{/*<Logo2 src="../static/amazon.jpg" alt="amazon_logo" />*/}
					75% of online shoppers use Amazon.
				</Description2>
				<Section>Team</Section>
				<Description>Insert Team images here</Description>
				{/*<Logo2 src="../static/alex.jpg" alt="alex.jpg" />*/}
			</Container>
		</div>
	);
};

export default Home;
